# Generated by Django 4.2.11 on 2024-03-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_link', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='blog.post')),
            ],
        ),
    ]
